# test out our code using docker
# env:global:TAG=xxx needs to be kept in sync manualy with the ./DESCRIPTION:Version:xxx field

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker

warnings_are_errors:  false

before_install:
  - docker build .

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "/draft/t1/_book/dissertation.pdf"
    - "/draft/t2/_book/dissertationportfolio.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master