# test out our code using docker

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker

warnings_are_errors:  false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build . ; fi

