# Build on OSX and linux (use our docker container)

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker

env:
 global:
  - REPO=$DOCKER_USER/stormdown

warnings_are_errors:  false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t $REPO . ; fi

# push our custom docker container to docker hub, env vars stored on travis-ci.org
# don't forget to set these at https://travis-ci.org/github/$GITHUB_USER/stormdown/...settings
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker login -u $DOCKER_USER -p $DOCKER_TOKEN ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export REPO=$GITHUB_USER/stormdown ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f Dockerfile -t $REPO:$COMMIT . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker tag $REPO:$COMMIT $REPO:$TAG ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker push $REPO ; fi
