# test out our code using docker
# env:global:TAG=xxx needs to be kept in sync manualy with the ./DESCRIPTION:Version:xxx field

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker

warnings_are_errors:  false

env:
  global:
   - REPO=markanewman/stormdown
   - TAG=0.0.2

before_install:
  - docker build .

after_success:
  - export REPO=$REPO
  - export TAG=$TAG

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  tag_name: $TAG
  file:
    - "/draft/t1/_book/dissertation.pdf"
    - "/draft/t2/_book/dissertationportfolio.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: $REPO
    branch: master