# test out our code using docker
# env:global:TAG=xxx needs to be kept in sync manualy with the ./DESCRIPTION:Version:xxx field

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker

warnings_are_errors:  false

env:
  global:
    GITHUB_USER: markanewman
    PACKAGE: stormdown
    REPO: $GITHUB_USER/$PACKAGE
    TAG: "2.0.4"

before_script:
  - docker images

script:  
  - docker build -t $REPO:$TAG .
  - docker run --name $PACKAGE $REPO:$TAG

before_deploy:
  - docker cp $PACKAGE:/draft/t1/dissertation.html dissertation.html

# only deploy when a new release was created
# https://github.com/{user}/{repo}/releases -> draft new release -> publish release
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  body: $TRAVIS_TAG
  file:
    - "dissertation.html"
  skip_cleanup: true
  overwrite: true
  on:
    repo: $REPO
    branch: master
    tags: true
