package <- 'stormdown'
working_dir <- getwd()
draft_dir <- paste0(working_dir, '/draft')
draft_t1_dir <- paste0(draft_dir, '/t1')
draft_t2_dir <- paste0(draft_dir, '/t2')
draft_t1_pdf <- paste0(draft_t1_dir, '/_book/dissertation.pdf')
draft_t2_pdf <- paste0(draft_t2_dir, '/_book/dissertationportfolio.pdf')
if (dir.exists(draft_dir)) unlink(draft_dir, recursive = T)
dir.create(draft_dir)
rmarkdown::draft(draft_t1_dir, template = 'dissertation', package = package, create_dir = T, edit = F)
rmarkdown::draft(draft_t2_dir, template = 'dissertationportfolio', package = package, create_dir = T, edit = F)
setwd(draft_t1_dir); env_t1 <- new.env(); bookdown::render_book('index.rmd', envir = env_t1)
setwd(draft_t2_dir); env_t2 <- new.env(); bookdown::render_book('index.rmd', envir = env_t2)
file.exists(draft_t1_pdf) & file.exists(draft_t2_pdf)
